### ISSUE TITLE
Fails and corrupts LogSeq commands

### ISSUE THREAD

**Issue by BobWalsh** [DenaroCF/Highlighters-for-Logseq#2]
followed the directions, and from thenon "/" would only show the first slash command. Settings>>Advanced>>Clear cache reset LogSeq to where it was before I attempted this plugin.

**Comment by charliie-dev** [comment]
same problem here.

**Comment by DenaroCF** [comment]
@BobWalsh, @charleschiu2012 That's not problem of the plugin, it's a Logseq problem. They fix it in the latest version of the app, pls update it. :)

**Comment by charliie-dev** [comment]
Hmmm, I'm already using the latest version (0.6.1) on win10; however, the problem still appears.
Thanks for the quick response! I will check with Logseq teams.

**Comment by charliie-dev** [comment]
After fewer investigation, It turns out that I misunderstood the way to install the plugins. I git clone the repo and load plugins from that repo floder, not knowing that I should actually use the release zip file. 🤣 Maybe @BobWalsh can give it another try.
Now the plugin works faultlessly! Sorry for bothering @DenaroCF !
